services:
  - type: web
    name: mamaafrica
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Mama Africa"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: "120"
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: redis
      - key: REDIS_CLIENT
        value: predis
      - key: REDIS_URL
        sync: false
      - key: REDIS_CACHE_DB
        value: "0"
      - key: MAIL_MAILER
        value: log
      - key: CLOUDINARY_URL
        sync: false
      - key: VITE_APP_NAME
        value: "Mama Africa"
